---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: simple-server 
  namespace: default 
spec:
  imageRepositoryRef:
    name: simple-server
  policy:
    semver:
      range: 1.0.x

