apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: charts
  namespace: flux-system
spec:
  interval: 1m
  url: git@github.com:jshaw86/fluxci-example-charts.git
  ref:
    branch: master
  ignore: |-
    # exclude all
    /*
    # include deploy directory
    !/deploy/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: simple-server
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./deploy/simple-server
      version: '1.0.x'
      sourceRef:
        kind: GitRepository
        name: charts
        namespace: flux-system
      interval: 1m
  values:
    image:
      tag: v1.0.0 # {"$imagepolicy": "flux-system:simple-server:tag"}
